package RajaTestScripts;

import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.LogStatus;

import CommonLibrary.WebDriverCommonLib;
import GenericLibrary.BaseClass;
import GenericLibrary.FileUtils1;
import ObjectRepository.AddContractor_Pkg_MonthlyPayroll_Page;

public class Divyesh_PayrollSwitch extends BaseClass {
	
	WebDriverCommonLib wb = new WebDriverCommonLib();

	String programmeName = "Program Name-PN-1";
	String Admin = "Roger Federer - Bella Jee";
	String projectAdmin = "Roger Federer - Bella Jee";
	String Sponsor = "HSBC-Sponsor - Vincent John";
	String Require_Payroll_ChkBox_Switch_Toltip_txt_Act = "Turning this switch on will add a mandatory confirmation message at the bottom of the Monthly Payroll screen. A text box will open  below the switch where the administrator can input the verbiage for the agreement. The Contractor will not be able to submit Payroll until reading the message and checking the agreement box on the Monthly Payroll screen.";
	String Require_Payroll_ChkBox_List = "Contract Number";
	String Require_Payroll_ChkBox_feild = "";
	String contractor = "Roger Federer Roger";
	String Hierarcytext = "Click here to view the Key Performance Indicators(KPIs) ";
	String CP_Contains_text = "Roger Federer";
	String Cp_Contains_text_status = "Missing Payroll";
	String EnrollPayroll_Seemore = "(See More)";
	String Month_jan = "January 2020";
	String Month_feb = "February 2020";
	String Month_mar = "March 2020";
	String Month_Apr = "April 2020";
	String Month_may = "May 2020";
	String Month_jun = "June 2020";
	String Month_jul = "July 2020";
	String Month_Aug = "August 2020";
	String Month_Sep = "September 2020";
	String classCode_Hours = "100";
	String Classcode_uncapped = "1000";
	String AlertMessage_CPkg_payroll = "You must read and agree to the confirmation message at the bottom of the Payroll Screen before submitting Payroll.";
    String Prog_name_NCP ="Program Name-PN-1";
    String proj_name_NCP="Project Name-PJN-1";
    String CP_name="Roger Federer";
    String CP_Satus = "Missing Payroll";
    String Contractor_Activitieslist="Payroll";
    
	@Test
	public void Payroll_ALert() throws Throwable {

	
	AddContractor_Pkg_MonthlyPayroll_Page.ProgrammeICon(driver).click();
		test.log(LogStatus.PASS, "Programme ICon is cicked succesfully");
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,0)");
		Thread.sleep(2000);
		AddContractor_Pkg_MonthlyPayroll_Page.AdvancesearchbarIcon(driver).click();
		test.log(LogStatus.PASS, "Adv search ICon is cicked succesfully");
		wb.selectByVisibleText(Admin, AddContractor_Pkg_MonthlyPayroll_Page.Select_Programme_Admin(driver));
		test.log(LogStatus.PASS, "Programme Admin is selected from DropDown");
		wb.selectByVisibleText(Sponsor, AddContractor_Pkg_MonthlyPayroll_Page.Select_Programme_SPonsor(driver));
		test.log(LogStatus.PASS, "Programme Sponsor  is selected from DropDown");
		AddContractor_Pkg_MonthlyPayroll_Page.searchBtnDownProgramme(driver).click();
		Thread.sleep(2000);
		test.log(LogStatus.PASS, "Search btn is clicked succesfully after adv search filters");
		js.executeScript("window.scrollTo(0,0)");
		Thread.sleep(4000);
		AddContractor_Pkg_MonthlyPayroll_Page.Edit_btn(driver).click();
		test.log(LogStatus.PASS, "Edit btn is clicked again after switch to main tab");
		wb.SwitchtonewTab();
		test.log(LogStatus.PASS, "switch to new  tab fist time");
		Thread.sleep(2000);
		//wb.click(AddContractor_Pkg_MonthlyPayroll_Page.Payroll_Cvtrack_Btn(driver));
		AddContractor_Pkg_MonthlyPayroll_Page.Payroll_Cvtrack_Btn(driver).click();
		test.log(LogStatus.PASS, "Payroll and Cv tracking button is clicked succesfully");
		Thread.sleep(2000);
		js.executeScript("window.scrollTo(0,200)");
		wb.TurnON_Switch(AddContractor_Pkg_MonthlyPayroll_Page.Require_Payroll_ChkBox_Switch);
		test.log(LogStatus.PASS,
				"Switched at payrolland cv tracking tab of  confirmation check box is handled succesfully");
		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.Require_Payroll_ChkBox_Switch_Alert(driver));
		test.log(LogStatus.PASS, "checked the alert whtehr present or not");
		wb.mouseOverElement(AddContractor_Pkg_MonthlyPayroll_Page.Require_Payroll_ChkBox_Toltip(driver));
		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.Require_Payroll_ChkBox_Switch_Toltip_txt(driver),
				Require_Payroll_ChkBox_Switch_Toltip_txt_Act);
		Thread.sleep(2000);
		test.log(LogStatus.PASS, "Text at Requiredocument page is validated");
		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Require_Payroll_ChkBox_TokenList, Require_Payroll_ChkBox_List);
		test.log(LogStatus.PASS, "selected the token name for payrollconfirmation check box");
		System.out.println("programm filter is done");
		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		Thread.sleep(2000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SavenadCloseBtn_payroll_CV_progrm(driver));
		Thread.sleep(2000);
		wb.Switchtoparent();
		test.log(LogStatus.PASS, "Switched to parent tab");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.HomeIcon(driver));
		test.log(LogStatus.PASS, "clciked on  to Home page");
		Thread.sleep(2000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.projectICon(driver));
		test.log(LogStatus.PASS, "clicked on  to project Icon");
		js.executeScript("window.scrollBy(0,0)");
		Thread.sleep(2000);
		AddContractor_Pkg_MonthlyPayroll_Page.AdvancesearchbarIcon(driver).click();
		test.log(LogStatus.PASS, "Adv search ICon is cicked succesfully");
		wb.selectByVisibleText(Admin, AddContractor_Pkg_MonthlyPayroll_Page.ProgrammAdmin_Project(driver));
		test.log(LogStatus.PASS,"Programme Admin at project level is selected");
		Thread.sleep(2000);
		wb.selectByVisibleText(Admin, AddContractor_Pkg_MonthlyPayroll_Page.projectAdmin_project(driver));
		test.log(LogStatus.PASS,"project Admin at project level is selected");
		Thread.sleep(2000);
		wb.selectByVisibleText(Sponsor, AddContractor_Pkg_MonthlyPayroll_Page.ProgrammSponsor_project(driver));
		test.log(LogStatus.PASS,"Programme Sponsor at project level is selected");
		Thread.sleep(2000);
		AddContractor_Pkg_MonthlyPayroll_Page.searchBtnDownProgramme(driver).click();
		Thread.sleep(4000);
		test.log(LogStatus.PASS, "Search btn is clicked succesfully after adv search filters");
		js.executeScript("window.scrollTo(0,0)");
		Thread.sleep(4000);
		AddContractor_Pkg_MonthlyPayroll_Page.Edit_btn(driver).click();
		test.log(LogStatus.PASS, "Edit btn is clicked again after switching  to main tab");
		wb.SwitchtoChild1();
		test.log(LogStatus.PASS, "switched to child window at project");
		Thread.sleep(2000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.Project_MoreBtn(driver));
		Thread.sleep(2000);
		test.log(LogStatus.PASS, "More button is clicked is succesfully");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.Payroll_CV_project_Btn(driver));
		test.log(LogStatus.PASS, "Payroll and CV  tab is clicked at project level");
		Thread.sleep(2000);
		wb.TurnOFF_Switch(AddContractor_Pkg_MonthlyPayroll_Page.payRollSetting_Changes_Project);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.Save_Clsoe_Btn_Payroll_Project(driver));
		wb.Switchtoparent();
		test.log(LogStatus.PASS, "Switched to parent tab at Project level");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.HomeIcon(driver));
		test.log(LogStatus.PASS, "clciked on  to Home page");
		Thread.sleep(2000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.ProgrammeICon(driver));
		test.log(LogStatus.PASS, "clicked on  to Programme Icon");
		js.executeScript("window.scrollBy(0,0)");
		AddContractor_Pkg_MonthlyPayroll_Page.AdvancesearchbarIcon(driver).click();
		test.log(LogStatus.PASS, "Adv search ICon is cicked succesfully");
		wb.selectByVisibleText(Admin, AddContractor_Pkg_MonthlyPayroll_Page.Select_Programme_Admin(driver));
		test.log(LogStatus.PASS, "Programme Admin is selected from DropDown");
		wb.selectByVisibleText(Sponsor, AddContractor_Pkg_MonthlyPayroll_Page.Select_Programme_SPonsor(driver));
		test.log(LogStatus.PASS, "Programme Sponsor  is selected from DropDown");
		AddContractor_Pkg_MonthlyPayroll_Page.searchBtnDownProgramme(driver).click();
		Thread.sleep(2000);
		test.log(LogStatus.PASS, "Search btn is clicked succesfully after adv search filters");
		js.executeScript("window.scrollTo(0,0)");
		Thread.sleep(4000);
		wb.switchToFrameById( "ifrmPreview");
		wb.mouseOverElement(AddContractor_Pkg_MonthlyPayroll_Page.HierachyButton(driver));
		wb.CompareTextandClick(AddContractor_Pkg_MonthlyPayroll_Page.HierachyButton(driver), Hierarcytext,
				AddContractor_Pkg_MonthlyPayroll_Page.HierarchyBtn_txt_graph(driver));
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.Programme_Frame(driver));
		Thread.sleep(2000);
		wb.CP_status_filters(AddContractor_Pkg_MonthlyPayroll_Page.Contrctr_list_frame, AddContractor_Pkg_MonthlyPayroll_Page.Contrctr_Status_list_frame,
				CP_Contains_text, Cp_Contains_text_status);
		System.out.println(driver.getWindowHandles());
		wb.SwitchtonewTab();
		Thread.sleep(4000);
		wb.switchToFrameById( AddContractor_Pkg_MonthlyPayroll_Page.Enrollment_frame);
		test.log(LogStatus.PASS, "Switched to frame at Enrollmentpage at Contracot apckage level");
		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Enrollment_List, EnrollPayroll_Seemore);
		test.log(LogStatus.PASS, "Enrollment see more btn at Payroll is selected succesfully");
		Thread.sleep(2000);
		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_jan);
		test.log(LogStatus.PASS, "Jan payroll is clicked succesfully");
		System.out.println(driver.getWindowHandles());
		wb.SwitchtoChild2();
		System.out.println(driver.getWindowHandles());
		Thread.sleep(2000);
		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(driver), classCode_Hours);
		test.log(LogStatus.PASS, "ENtered the class code hour for jan 2020 payroll");
		Thread.sleep(2000);
		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(driver), Classcode_uncapped);
		test.log(LogStatus.PASS, "ENtered the class code hour for jan 2020 payroll");
		Thread.sleep(2000);
		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage(driver));
		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
		Thread.sleep(2000);
		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(driver), AlertMessage_CPkg_payroll);
		test.log(LogStatus.PASS, "Alert message validated succesfully");
		Thread.sleep(2000);
		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage(driver));
		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage(driver));
		test.log(LogStatus.PASS,
				"Save and close button is clicked succesfully after validating the alert and check box");
		Thread.sleep(4000);
		wb.Switchtoparent();
		js.executeScript("window.scrollTo(0,0)");
		AddContractor_Pkg_MonthlyPayroll_Page.Edit_btn(driver).click();
		test.log(LogStatus.PASS, "Edit btn is clicked again after switching  to main tab");
		wb.SwitchtonewTab();
		Thread.sleep(2000);
		wb.launchUrl(GenericLibrary.ExcelLibraray_Hashmap.getCellData("NCP", 1));
		test.log(LogStatus.PASS, "NCP portal url is navigated ");
		wb.typeBySendkeys(GenericLibrary.ExcelLibraray_Hashmap.getCellData("NCPUNProJ-1", 1), AddContractor_Pkg_MonthlyPayroll_Page.NCP_UN_Feild(driver));
		test.log(LogStatus.PASS, "Username is entered at NCP UN feild");
		wb.typeBySendkeys(GenericLibrary.ExcelLibraray_Hashmap.getCellData("NCPPWProJ-1", 1), AddContractor_Pkg_MonthlyPayroll_Page.NCP_PW_Feild(driver));
		test.log(LogStatus.PASS, "Password is entered at NCP PW feild");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_LOgin_Btn(driver));
		test.log(LogStatus.PASS, "Login button  is clicked at NCP login button feild");
		Thread.sleep(2000);
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Prog_List, Prog_name_NCP);
//		Thread.sleep(2000);
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.NCP_proj_List, proj_name_NCP);
//		Thread.sleep(2000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_MyProject_tab(driver));
		test.log(LogStatus.PASS, "My project tab is clicked  at NCP");
	    wb.typeBySendkeys(proj_name_NCP, AddContractor_Pkg_MonthlyPayroll_Page.NCP_List_SearchBar(driver));
		test.log(LogStatus.PASS,"project name is selcte" +" : proj_name_NCP "); 
	    Thread.sleep(2000);
	    wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Proj_Actve_btn(driver));
	    Thread.sleep(2000);
	    js.executeScript("window.scrollTo(0,300)");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_HirerarchyBtn(driver));
		Thread.sleep(3000);
		wb.NCP_Filters(AddContractor_Pkg_MonthlyPayroll_Page.NCP_CP_LIST_FILTERS, AddContractor_Pkg_MonthlyPayroll_Page.NCP_CP_Status_list, CP_Contains_text, Cp_Contains_text_status);
		wb.SwitchtoChild3();
		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.NCP_MyContracts_list, "Missing Payroll");
	    js.executeScript("window.scrollTo(0,400)");
	    wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Contractor_Activities, Contractor_Activitieslist);
	    Thread.sleep(3000);
		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Payroll_Monthlist, Month_jan);
		Thread.sleep(2000);
		wb.NCP_CHKBOX_Validation(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Payroll_ChkBox);
		js.executeScript("window.scrollTo(0,400)");
		wb.isDisplayed( AddContractor_Pkg_MonthlyPayroll_Page.NCP_Chkbox_Disabled_txt(driver));
		System.out.println("Not enabled");
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Payroll_saveBtn(driver));
		Thread.sleep(4000);
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_Chkbox_Cancel_btn(driver));
		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.NCP_payroll_Mnth_CancelBtn(driver));
		wb.SwitchtoMainTab();
		js.executeScript("window.scrollTo(0,0)");
		test.log(LogStatus.PASS, test.addScreenCapture(FileUtils1.captureScreen(driver,"Payroll_ALert")));
		
		
		
		
		

//		test.log(LogStatus.PASS, "Switched to Contractor package tab again for feb -2020 payroll");
//		wb.switchToFrameById( "ifrmPreview");
//		test.log(LogStatus.PASS, "Switched to frame at COntractor packages tab");
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_feb);
//		test.log(LogStatus.PASS, "Feb payroll-2020 is clicked succesfully to enter the data");
//		wb.SwitchtoChild1(driver);
//		System.out.println(driver.getWindowHandles());
//		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(), classCode_Hours);
//		test.log(LogStatus.PASS, "ENtered the class code hour for Feb 2020 payroll");
//		Thread.sleep(2000);
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(), Classcode_uncapped);
//		test.log(LogStatus.PASS, "ENtered the class code hour for Feb 2020 payroll");
//		Thread.sleep(2000);
//		wb.UNTick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
//		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(), AlertMessage_CPkg_payroll);
//		test.log(LogStatus.PASS, "Alert message validated succesfully");
//		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
//		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS,
//				"Save and close button is clicked succesfully after validating the alert and check box");
//		System.out.println(driver.getWindowHandles());
//		wb.SwitchtonewTab();
//		test.log(LogStatus.PASS, "Switched to Contractor package tab again for Mar -2020 payroll");
//		wb.switchToFrameById( "ifrmPreview");
//		test.log(LogStatus.PASS, "Switched to frame at COntractor packages tab");
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_mar);
//		test.log(LogStatus.PASS, "March payroll-2020 is clicked succesfully to enter the data");
//		wb.SwitchtoChild2(driver);
//		System.out.println(driver.getWindowHandles());
//		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(), classCode_Hours);
//		test.log(LogStatus.PASS, "ENtered the class code hour for Mar 2020 payroll");
//		Thread.sleep(2000);
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(), Classcode_uncapped);
//		test.log(LogStatus.PASS, "ENtered the class code hour for Mar 2020 payroll");
//		Thread.sleep(2000);
//		wb.UNTick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
//		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(), AlertMessage_CPkg_payroll);
//		test.log(LogStatus.PASS, "Alert message validated succesfully");
//		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
//		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS,
//				"Save and close button is clicked succesfully after validating the alert and check box");
//		System.out.println(driver.getWindowHandles());
//		wb.SwitchtonewTab();
//		System.out.println(driver.getWindowHandles());
//		test.log(LogStatus.PASS, "Switched to Contractor package tab again for Apr -2020 payroll");
//		wb.switchToFrameById( "ifrmPreview");
//		test.log(LogStatus.PASS, "Switched to frame at COntractor packages tab");
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_Apr);
//		test.log(LogStatus.PASS, "March payroll-2020 is clicked succesfully to enter the data");
//		wb.SwitchtoChild1(driver);
//		System.out.println(driver.getWindowHandles());
//		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(), classCode_Hours);
//		test.log(LogStatus.PASS, "ENtered the class code hour for April 2020 payroll");
//		Thread.sleep(2000);
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(), Classcode_uncapped);
//		test.log(LogStatus.PASS, "ENtered the class code hour for April 2020 payroll");
//		Thread.sleep(2000);
//		wb.UNTick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		Thread.sleep(2000);
//		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
//		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(), AlertMessage_CPkg_payroll);
//		Thread.sleep(2000);
//		test.log(LogStatus.PASS, "Alert message validated succesfully");
//		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
//		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS,
//				"Save and close button is clicked succesfully after validating the alert and check box");
//		System.out.println(driver.getWindowHandles());
//		wb.SwitchtonewTab();
//		System.out.println(driver.getWindowHandles());
//		test.log(LogStatus.PASS, "Switched to Contractor package tab again for may -2020 payroll");
//		wb.switchToFrameById( "ifrmPreview");
//		test.log(LogStatus.PASS, "Switched to frame at COntractor packages tab");
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_may);
//		test.log(LogStatus.PASS, "Apr payroll-2020 is clicked succesfully to enter the data");
//		wb.SwitchtoChild1(driver);
//		System.out.println(driver.getWindowHandles());
//		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(), classCode_Hours);
//		test.log(LogStatus.PASS, "ENtered the class code hour for may 2020 payroll");
//		Thread.sleep(2000);
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(), Classcode_uncapped);
//		test.log(LogStatus.PASS, "ENtered the class code hour for May 2020 payroll");
//		Thread.sleep(2000);
//		wb.UNTick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		Thread.sleep(2000);
//		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
//		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(), AlertMessage_CPkg_payroll);
//		Thread.sleep(2000);
//		test.log(LogStatus.PASS, "Alert message validated succesfully");
//		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
//		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS,
//				"Save and close button is clicked succesfully after validating the alert and check box");
//		System.out.println(driver.getWindowHandles());
//		wb.SwitchtonewTab();
//		System.out.println(driver.getWindowHandles());
//		test.log(LogStatus.PASS, "Switched to Contractor package tab again for may -2020 payroll");
//		wb.switchToFrameById( "ifrmPreview");
//		test.log(LogStatus.PASS, "Switched to frame at COntractor packages tab");
//		wb.Filter(AddContractor_Pkg_MonthlyPayroll_Page.Monthsly_payrollTablelist, Month_may);
//		test.log(LogStatus.PASS, "May payroll-2020 is clicked succesfully to enter the data");
//		wb.SwitchtoChild1(driver);
//		System.out.println(driver.getWindowHandles());
//		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Hours_Feild(), classCode_Hours);
//		test.log(LogStatus.PASS, "ENtered the class code hour for June 2020 payroll");
//		Thread.sleep(2000);
//		wb.type(AddContractor_Pkg_MonthlyPayroll_Page.Class_Code_Uncapped_Payroll(), Classcode_uncapped);
//		test.log(LogStatus.PASS, "ENtered the class code hour for June 2020 payroll");
//		Thread.sleep(2000);
//		wb.UNTick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Un ticked the chck box at payroll confirmgation of Contarctor package");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Save and close button is clicked succesfully");
//		Thread.sleep(2000);
//		wb.Compare(AddContractor_Pkg_MonthlyPayroll_Page.AlerMsg_OK_SaveandCloseBtn_CPkg_PayrollPage(), AlertMessage_CPkg_payroll);
//		Thread.sleep(2000);
//		test.log(LogStatus.PASS, "Alert message validated succesfully");
//		wb.Alert_Click(AddContractor_Pkg_MonthlyPayroll_Page.OK_SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS, "Alert is handled with and  without web elemenent present");
//		wb.Tick_CheckBox(AddContractor_Pkg_MonthlyPayroll_Page.payRoll_ChkBox_CP);
//		test.log(LogStatus.PASS, "Ticked the chck box at payroll confirmgation of Contarctor package alert message");
//		wb.click(AddContractor_Pkg_MonthlyPayroll_Page.SaveandCloseBtn_CPkg_PayrollPage());
//		test.log(LogStatus.PASS,
//				"Save and close button is clicked succesfully after validating the alert and check box");
//		System.out.println(driver.getWindowHandles());
//		wb.SwitchtonewTab();
//		System.out.println(driver.getWindowHandles());
	}
}
